workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest  # Use the latest Xcode version
      cocoapods: default  # Ensure CocoaPods is available

    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: Get Flutter packages
        script: flutter pub get

      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-method app-store  # Can be 'ad-hoc' or 'development' if testing

    artifacts:
      - build/ios/ipa/*.ipa  # Correct path for iOS artifacts
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
